# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = '2048'
    vb.cpus = '2'
  end

  config.omnibus.chef_version = '12.9.41'

  config.vm.provision 'chef_solo' do |chef|
    chef.add_recipe 'test-cookbook::test1'
    #chef.add_recipe 'test-cookbook::test2'
    #chef.add_recipe 'test-cookbook::test3'
  end

end
